### ISSUE TITLE
Tracking scripts not loading

### ISSUE THREAD

**Issue by hannahwoodward** [ben-rogerson/nuxt-seomatic-meta#1]
First of all, thanks for creating this plugin! It's been super easy to integrate into our Nuxt/Craft setup.

I'm seeing an issue where tracking scripts don't seem to be running on page load/change. Had a quick look into the source code, and found that I think the trouble might be this line https://github.com/ben-rogerson/nuxt-seomatic-meta/blob/f5d3c747be474ad9503e7a03ffd02654badb4faf/lib/plugin.js#L105 

as (I believe) SEOmatic seems to return these scripts already in a string. Removing the extra stringifying so that the line becomes `innerHTML: script` seems to fix the issue.

**Comment by ben-rogerson** [comment]
Hey Hannah, thanks for letting me know about that issue.
I've now fixed and updated the tracking scripts (https://github.com/ben-rogerson/nuxt-seomatic-meta/commit/1fe184eaf4f3586dc352c1b80e635917930f0601).

Please let me know if you come across anything else :)
