### ISSUE TITLE
When will there be multisite support?

### ISSUE THREAD

**Issue by Toni-hr98** [ben-rogerson/nuxt-seomatic-meta#2]
This would be awesome... :)

**Comment by ben-rogerson** [comment]
I'm pretty busy at the moment, but I'm accepting pull requests 👍

**Comment by Toni-hr98** [comment]
Here you go:

https://github.com/Toni-hr98/nuxt-seomatic-meta.git

Now you can add your siteId and it will do its work 💯 

```
  return {
                headData: await app.seomaticMeta(route, siteId),
  }
```

**Comment by ben-rogerson** [comment]
Thanks Toni, I've now updated the plugin
