### ISSUE TITLE
Getting CORS errors on live site

### ISSUE THREAD

**Issue by peirix** [ben-rogerson/nuxt-seomatic-meta#6]
We've set this up on a project and got it working locally (with the workaround mentioned in #4 )

But now that we've pushed the project to a live server we're just getting CORS errors. All our other graphql requests go through fine (using apollo), which leads me to think that there's got to be something in the way this is set up?

**Comment by ben-rogerson** [comment]
hey peirix, did you end up finding the issue here?

**Comment by peirix** [comment]
No. I ended up copying out the plugin code into my `nuxtServerInit` and storing it in a store variable :(

**Comment by ben-rogerson** [comment]
Doh, sorry about that.
I haven't noticed the same issue but I've pushed an update a few days back that was breaking things with the [`metaJsonLdContainer`](https://github.com/ben-rogerson/nuxt-seomatic-meta/pull/7/files#diff-11af61311ab29f43ed180a25e84cbae6a92c72a244b8c4f717d573ec930ff5acL112).
You're free to give it another go, it might have fixed those cors issue.
